name: DevSecOps CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t juice-shop:latest .

      - name: Test Docker image
        run: docker run --rm juice-shop:latest node --version
